### ISSUE TITLE
Get error when updating the submodules

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [thu-ml/realsafe#2]
Hello, I got an error when updating submodules.
Error log:
```
fatal: 引用不是一个树：c6e893728c3e7355e3bc689352011a55798b0e95
无法在子模组路径 'third_party/models' 中检出 'adc01cd76ae0d9d3b2e8dde3ec6bf4086f7da046'
无法在子模组路径 'third_party/trades' 中检出 'c6e893728c3e7355e3bc689352011a55798b0e95'
```
Is there any solutions?

**Comment by Fugoes** [comment]
Please using these commands:
```shell
git clone https://github.com/thu-ml/realsafe
cd realsafe/
git submodule init
git submodule update --depth 1
```
If these errors still occur, please check your network stability. Some of the submodules are large, and git clone does NOT support resuming from previous failed download.

What's more, github.com has gone down several times recently.

**Comment by Wenzhao-Xiang** [comment]
@Fugoes  Thanks for your replying. I just followed the instructions you mentioned, and have tried several times yesterday, but all of them failed. I don't know what went wrong. By the way, it seems that only the submodules 'tensorflow/models' and 'trades' got this error.
 Finally, I can just use the following workaround:
```
git clone repo
git reset --hard commit
```
