### ISSUE TITLE
About the adversarial defense model on CIFAR-10 and ImageNet in Keras or higher tensorflow

### ISSUE THREAD

**Issue by momo1986** [thu-ml/realsafe#3]
Hello, thanks for sharing.

Is there the adversarial training model for defense available in Keras or higher tensorflow in ImageNet and CIFAR-10?

Where can I refer to it?

Thanks & Regards!

**Comment by Fugoes** [comment]
> Is there the adversarial training model for defense available in Keras or higher tensorflow in ImageNet and CIFAR-10?

All models provided in the `example/` folder are thin wrappers around third-party code. For now, these third-party code all use either TensorFlow 1.x or PyTorch. If you want to use these third-party TensorFlow 1.x code with TensorFlow 2.x, you might find https://www.tensorflow.org/guide/upgrade useful.

> Where can I refer to it?

You could find their original code repos' URL in the header of these wrappers under `example/` folder.

**Comment by momo1986** [comment]
> > Is there the adversarial training model for defense available in Keras or higher tensorflow in ImageNet and CIFAR-10?
> 
> All models provided in the `example/` folder are thin wrappers around third-party code. For now, these third-party code all use either TensorFlow 1.x or PyTorch. If you want to use these third-party TensorFlow 1.x code with TensorFlow 2.x, you might find https://www.tensorflow.org/guide/upgrade useful.
> 
> > Where can I refer to it?
> 
> You could find their original code repos' URL in the header of these wrappers under `example/` folder.

@Fugoes Fu, thanks for your reply.

If I want to use the module of adversarial training in tensorflow in RealSafe? 

Which directory and which file should shoud I refer?

Thanks & Regards!

**Comment by Fugoes** [comment]
> If I want to use the module of adversarial training in tensorflow in RealSafe?

We provide ONLY wrappers for third-party pre-trained adversarial training models. You could find their adversarial training code in the original code repo. You could use attacks in RealSafe to do adversarial training in your own code though.

**Comment by momo1986** [comment]
Hello, @Fugoes .

Thanks for your kind answer.

Best Regards!
Jun Yan
