### ISSUE TITLE
NotFoundError  in test_imagenet_models.py

### ISSUE THREAD

**Issue by Dxy-tju** [thu-ml/realsafe#7]
Hello, we met an error when we run "python test_imagenet_models.py"

We run "python realsafe/example/imagenet/ens4_adv_inception_v3.py" and checked out that three chekpoint files have been downloaded successfully.

But the error occurred like:

> NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. 

![25a1768cfde26e3b3e9d0328810cc29](https://user-images.githubusercontent.com/52737244/95844942-1e46e300-0d7c-11eb-808f-fe49f98ba8c8.png)

**Comment by Fugoes** [comment]
> We run "python realsafe/example/imagenet/ens4_adv_inception_v3.py" and checked out that three chekpoint files have been downloaded successfully.

The original ens4_adv_inception_v3 model conflicts with inception_v3 model, so we use another scope name `Ens4InceptionV3` and convert the scope name after the original checkpoint downloaded. This is done in https://github.com/thu-ml/realsafe/blob/master/example/imagenet/ens4_adv_inception_v3.py#L52. Please make sure this step has succeed.

What's more, some of the functionality of RealSafe requires GNU Linux and does not work under Windows.
